version: "3.8"
services:
  db_spotify:
    image: postgres:13.3
    container_name: db_spotify
    env_file:
      - .env
  tgbot:
     build:
         context: .
         dockerfile: Dockerfile
     container_name: tgbot
     env_file:
       - .env
     depends_on:
       - db_spotify